services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17-bookworm
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: '123456'
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -d $$POSTGRES_DATABASE -U $$POSTGRES_USER]
      interval: 10s
      timeout: 5s
      retries: 5
